services:
  web:
    build:
      context: ./../..
      dockerfile: apps/fastapi/Dockerfile
    env_file:
      - ../../packages/database/.env
    volumes: # hot reload
      - .:/app/apps/fastapi
    ports:
      - 8000:8000
    restart: always
